[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "e046fa09ad31adb7e841a50196dcba09d2f61224"
os = "macos"

    [[DAQP.download]]
    sha256 = "d010d215baff75928bcc498c82720c9c5eef1f0ef4064ca58abf9975a7f8bb0d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "ccba2d0d1f87615123f5fe73058ac2530effaaad"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "3a636a59fe1b977120ccf1a8c4dda0f02ef7b672309e6aebbb61a7be98c593d2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "d29de5ae268a2ff61cfe8771e6492af381bc8701"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "b8e9da91f5c78e5680f0baf847863e645f27872be42de4a3dc9f4aaa5ac5ab13"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "01a57802582c49c467d921fcc1c61e60ece42fc7"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "2aa69dbbb325b2a3b075b13f00a7bc8ec5146d2709d510d6abd85d749a9c4e08"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87025191fe12774026fb271580ef8cbc2f04f067"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "794bce448ed5b6bc49446b4cbed019644208784af63edd93782c0e2634416909"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99406c0d5a065605ec4421bf5a8e7474c8f66768"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "a678025dc8028ee8ee0a2404f485e279e5c7cbfda28086819eeae8d26a342c9c"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5aa37cd05c072983f877c0af0a7d5d212887753a"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "fd7509730ee290a053f2094a602cdfc77cb4aee3967b55b1cd04aebe90a0d772"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78cf616a2a7279e701528facbe21d428d93b4b83"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "2b092d0b1b92d923c7736cc1659fa7e538f4eb1430b6a2266c81b9b2604a724d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "e1f955357cb9714a829a4317628a283cced3383d"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "a170441dc5bf348466287fc7e67e9738842fe20e549c1a88034196f34de4b3fe"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "018cfe195d1d82e4a3b9f6f4f5f933bcbfc5ba95"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "171f8d0afd6ce37aa4625f16657436035f55b3db7c56fe507287587737928f65"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "ae235f69792983f2dc8e78d790be2d27410d1778"
os = "windows"

    [[DAQP.download]]
    sha256 = "6b067bd59cba98c81c173e908f658e97c84764cf8bdb00d20126ddd3b03e44e8"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "e746f835cceae2aaabc13936f4e1b79d0b235247"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "919209ce2f8e329f61b2145cd514701fd98a4738439d64248f4845934d896c4b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "d890043761bb71d902fa1e0adee13968cdbc06a5"
os = "macos"

    [[DAQP.download]]
    sha256 = "17b2003bb3481aaa625b4554f62a4c26d62e9eff7312078ae0e40907e6e71884"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "a7e2955962b566ecd2d3007fc08b081b87a251ab"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "01c2a0b85788bf2efab49ca26d0e17434ddf2912d5f15714e850eba5967eca51"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "f141ddd20d23081dda5d5b956bdff68ae74c5c27"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "15088cfa856f793ee540a4fc05c6d870bac16a89a97e180f7be20eaee72941ce"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "b824a23cb78253d9a9bcce16f551bb3b00cd1edc"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "723927a61e0ba790850107e3acc5ccf28408cdc76bc41f56c685d2dd291c8d62"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "3296aa0e81159578ec82baa1891dbd5c399f99b3"
os = "windows"

    [[DAQP.download]]
    sha256 = "54aebd99f00f175f3c94f279813b56c28bf8930b230e9b5935e7f1bf19400e4d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.6.0+0/DAQP.v0.6.0.x86_64-w64-mingw32.tar.gz"
