[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "4ea07ca90670bd21ea96337ef394cd446b3ddeea"
os = "macos"

    [[DAQP.download]]
    sha256 = "195f16ff32bef44c3aac8b51024ee9908bf926af18224ecda7bfad86d0b410f8"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b9eb7215632593b68b493ae0681b48c320810531"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "d13f18e5eceb94d2541014b0272b1ee00964970398f23405b635d5ebd77bf4d5"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "070936415467755efd34ddc020e33bdebda5d20f"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "6cb4fd01384a996434ea214028c5854a17906d888417a46722a202f268edc8c2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "ec5721e8c7bc5a4a6b1326a4098f48d936f06973"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "2f13cc54c1dba14fb26993aedd45f6e7f46bee6b471c4e75229e465e72157af2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a04906f93b8b7abce10eb89dfaa939c690a80e1"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "5e3b42463f708820e95b040be943a3fe07391b796daa8d9e66abcecd415f9b23"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e630e29c250775ed56fb138f55bc49879fd94b27"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "39fad9637d737b08d037eff11ef5f863eb6b5ce402ee0c70fc8f98d4e3876113"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b7163e7bd7685b3018b65f6905e955a42fd62f0"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "65f83cf661c9215d8afe075509fbffab6ab7da6568fb010cac79c1d738aee1bd"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "701fbcfc6c00445092c75237cfa9044d635240fa"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "1c64e24fd9ccb4fad0e916e89a041c65da7105f3558c39b39ae0b44a0bac34a6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "dc97cceeecac1dbca6ca8c9aedd00f2c73c06dd8"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "67583ce7adc7d28537684b663775d0def9f073e8d55fac72bed86d1cd2082bd0"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "d311888ba3da125c4d761a0238ce79682eac2762"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "95b3afbd94154ec6b7d253ac2630b3fdd007490ed0f71dc776d99626e5de5d50"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "f67d8d1d7dd7c8fab2aa48ae5a6b28109d997413"
os = "windows"

    [[DAQP.download]]
    sha256 = "b6e058dd404730bbbdbfee17886e9b4e4e4ebf11820b33393cb3f36ce2ae6663"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "5676f3da48a18188d1f4fe6cc2b0cad2aa56a6bb"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "7be672387984c8d982cd81d30cef551ae409edfb28f7a6ec1f78b33925d35e46"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "956b28aead0be53c76986d27ce63936e3a9c8999"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "145376bb40cffbde3d4d45581b3902d41a392ad58e03100fe1b18af421151cf4"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "73678c78cfeaaf92e68baec49f09e8fd7f3769c7"
os = "macos"

    [[DAQP.download]]
    sha256 = "ba38596188b16e4f6f63c86de7beb3262743993a559e3cf9446f4732915a7e25"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "2eb41b5cf8bd471f3ba42b125ccbc6957c793bbe"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "be267219ff351a7ef6833ecc67bea8c00d8297014c2f4db217d43afd7db20d86"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "4b1fae75c5a75fc9e3bb0e5cfbb8107f49533bee"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "0448555ffdb49c4fefd5511d321474d646556a0002017234fa30262664f856f3"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "b4129f801f9bb9028d5f7db820c4762269607a6e"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "5e0395a208c890306f388f580a5fa8f1e80b17efba77d3f6cf380057bd92f26a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "34c3cc7b58ee39108f082597c185ee550ba5fb76"
os = "windows"

    [[DAQP.download]]
    sha256 = "4a475f51936344842ae3c436ddbb3669bfde65013034af5234adc5a4f0a62723"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.2+0/DAQP.v0.7.2.x86_64-w64-mingw32.tar.gz"
