[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "2dfb300bdd278cacb83cf684ab4e95dbf39ac96e"
os = "macos"

    [[DAQP.download]]
    sha256 = "60e81be4e1c07d04a6093f347aac4cfc5d10c2790f581ac5dbba1014f0740438"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "4ad82bbf699a0a7eacaf7a82cb8580dd65c52e0b"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "9ff505e8db05869780626a2b1ddc73d14716f29806ccf581e6d865c67866b5b5"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "8b92fb7fc8235af5288611a1302630d7eec26b78"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "7257da3784aefbd8bc70dacc27947f5f5675ee3e84882019137b33e51115fa56"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "d195ba3835c9bde5ce1c6b957768bfca2fdc93ed"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "0c7c9856b1caee7b0b9c2c48812a414ec0f1a333b8d6e7462a3b7c57ded41e1e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d7a2311f7397b48c2ff5ba4a4e2f19716a5ef24f"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "6ff74b8a1b23931f5d76359c2898d5687553068d0c805010032a899294b9f1a1"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46db926e48f151e5d29ec1b1588bed190f135c78"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "43b5e93ebccf817b9b935b9d1af32a8e23c27de11b49932fb6c32aa562ce748a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "deda4f802ee275b004c5b72bf2b3d93c51c73e5c"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "95fedc1a02ff66c00cdef3be466d1af23f9bad1dda6b99989ae38085a439eb81"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04c09bf39b0384ab316f3dc9bb2636217aee1353"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "7159513a09613fcfe598d0559760898a3f442465afe58166dca222f3961496ae"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "4fb2e3d43cb0cea030c7961ef790fb02c16adc50"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "c97f8c76f868530ff593e4d1dfda79390b3972f770ea5eb022566e8eab2e206b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "09b40544bb63e7d7bbc1ff53ea14e9691ba16482"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "6f2912036afac00ffff22844661b93bdc40f3fef3fdf17804d9b703c0397b833"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "97a62856a1fd4de56d99385300c5f9d449a28d6e"
os = "windows"

    [[DAQP.download]]
    sha256 = "43ec4c6d6ba6ad8e72864f8cf2b8621736dd1e8ca2aa2fcbbfd44c9ac141b0fa"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "9341d3fbc280c0090924adc9bd6b75b1a368d9b4"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "ba9cb1c1128b63a8dbc7833d0d87cef3e8ca1bdd6c1bdbd0f903635a54bc4a1b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "334a1622d05fee95778b13f1d1940bc1da4af176"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "555f27b4ca0d62e2c8088e62843821c91e528f5819cab09b95802beb1d0dcbc7"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "5fad5a8db1f9a93012b42495e1a5e1edf42ca474"
os = "macos"

    [[DAQP.download]]
    sha256 = "93a60cf734c2bf60262953290e9ff1f620ab2ed7d7afe04e53720b9e2beda6ba"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "73e4afb8d7b440ab80cdeeabefa66b1ae27ff34c"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "7f9b62dbf5d34b4b3da01388693b13547131abea13b20e9bf416418f6785ffd6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "f38b8df83bfaa6364f1a2d2d758365e48f09f4bf"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "37c82e73445dff2b3caaf7f5b2eda1512773eeec5acaa87f2cae6c09f348b01f"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "11598ab2ce65f314bfad9b64cb06e7d416111956"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "3955a57cd7b92ce8fd2cab887745d6bab06a8b5098f3537a050bf1ae751f0ad6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "957b99506b90eb2f7bbdc2446a1b2e82e18946b0"
os = "windows"

    [[DAQP.download]]
    sha256 = "60faf615a3273eb5197779379859be32cc4a93ffe31605e511328b912778dcb7"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.9.0+0/DAQP.v0.9.0.x86_64-w64-mingw32.tar.gz"
