[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "93d4a14092966f8487bcd600016a6bc725d7c9e1"
os = "macos"

    [[DAQP.download]]
    sha256 = "c180d6916b2a752451a27f7f4356e5c574bec3248b10cc43f87718aca29f9f3e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "2db79bc6eb5ffceadf8e2052b7531c0802d2b1b6"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "961c774f1407e6ddc15d8a65e7db1efecad25037f00a06b50683626552b28064"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "d4b1e7e0272364bcc875251d280ca8c47d98400a"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "3c7bc11cb3da298010c9c1493737d8bb22323d42abd352cd905d44e781a49963"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b288fb39092971f1541e821314d40e117d835512"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "918cc971504465982bfc449691d76fb04b2cfb4d625083700553278c716e077f"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f62a68b279c07b46e0ba123d9dc263630723687"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f68dd8b6c4251c4c579c2a037c20d78bcbc0e59a11c99924ebe1cb15a805b110"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aa0640f6a422cbb61715e95326a8d2a721fcf359"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "01a97e91ff89b933c17b0a53714b46c2c1e5e5dcecd2d1064d9ea013d86f7a27"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a2e5816c3a9bf3f2e034e2ca63794c22424aafd"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "ca2605eb9ebca7091bab1ab838265373cae58bc60bd1a85055027f32c87b711a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b35675e781f3e064d8db1995433febca773770b"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "adc042ea87b0b28af429245b1bbad96abfb1577bf4ebee451b54bf0422703c11"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "fd179059ecb1b607e5587be5d4e2e041622f4168"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "fd4e422b59a2bd336e36935ad2a2f28bfcf677d515740bd884ac6b8cf5d5025c"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "6172a8de57addb023f922590caf5dfdcb4fcc5ea"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "1dce650e3a87d58257333dae008c92359c0bad2e0ab246026109140666045f88"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "d96ac1c0ff28e2f41c0c87814752f9011666ff19"
os = "windows"

    [[DAQP.download]]
    sha256 = "f1fa6c8439af06bdc7246ac8dd0cf24e6ec06a9c61e4905e009e5812538b95f9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "ae830391f5c99da3025d0a4c7707589dcea44365"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "0de13216119e7e3bcaa975b060553280f08083849210f126bcf32ae68c600650"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "2b71bfff6452804364841a667bba89a274a56c4d"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "62924265506a106b955e921b981ca8194c80ac2eef21bcba3facd736291dbc05"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "8cdf3dd12eccec295013fb2b72a32e0bf060e84a"
os = "macos"

    [[DAQP.download]]
    sha256 = "35415139914db039919edc8e9fd3a0e71197f5ed9a83539e8cd35925d78e17fe"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "906a740d678a3b5c0f262fee8c609e37912827cc"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "a2a13a8291c42020d4b60cb3aca1a5032e7890be939eb5707ef4cac8821ad77a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "38859a4ad3548118dde3f9b257d1fadc70c3fd35"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "842d211edcf33262064ad196d8b9dd29421de534b036ec971f245c96b7155dab"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "c5c9aedd0e918722751b1930c125195774811fe2"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "01d489f123d83e612e4a13342c3f6e9ad7ff5fe72844d4d7ec4ec997389c2031"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "a5aef36d4e8b2fb56127836c0e560f0ed69aaf6d"
os = "windows"

    [[DAQP.download]]
    sha256 = "54d24cb6e89374ca03a91945e7cb04f09706cff508115d0e718060c78c3e6a8c"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.0+0/DAQP.v0.7.0.x86_64-w64-mingw32.tar.gz"
