[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "c1d26d0f9bf9a8e9710292b668e51a26032ed798"
os = "macos"

    [[DAQP.download]]
    sha256 = "206184fe3b9df323b5e07697cc2358d75a7967b5297aaee2286fbecce5088a07"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "1f138998e6d117abc3a2ede21baa3a04e0130dca"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "38ea6c80d5c2cf0e5cbce826c9fe26a43e8a0fb97e05c4fc2f99118e77865020"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b104913e9b800d280f98af4974316564dac4a421"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "af06801219d3570cff7ef8d9589ec3f7a99ec6c14ff184e2e4088cfe5dc9e34d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "5b089e883f4fae642bb0fecd1facf33160d965c5"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "d1cfc7805ddb3f7ed6a33460e29d5ebdbd6cc765800b0b50e468402c5cc3e665"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "def84f750fc1bcfd28f54daa13be974770a47a0d"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "ca3e7a56e2f9cf9b9c70f4d1295e9397a282fa786504e62b624bfff0e5fc84d8"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02deee0663157b27217a0259927f03eb5006dcf1"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "89d6494bc1144b3eb4aeecde853fa3735d30f49090f2a551db040e325cf4985b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "49da34a2319f7030b63195dedd92bbeb5f2780ee"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "2e4358d8fe001ce6638ac1287cfddd3344e3f7d474eae4409b2629d2f1deb830"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d14fba21930ffaa29b9e10e5f161aa9e309c4ba3"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "519e6d36ef87531255fb581e42e3b08c9e402237f89bd2cab91c326e658cfeb6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "137d6eb516e11a4186e78678b6ca3a963d2f1d63"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "c4b5a7aa2ee907c289c908207250d1ca55af862a9a5bccedcf63386be80cf24f"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "ef450995c995243e4ae5d02ce139b2b9389558e1"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "992dc709794a6c64929e2669aac8747b381d91b106ca09265af08dac896380db"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "d4c3f79748d09195197f3d7e4909f31e90a17c39"
os = "windows"

    [[DAQP.download]]
    sha256 = "394d985527f037f69ccee711e9bb0381a710a4a03ad8c369333a889495af78eb"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "789904555ed9f28cb2f40c238cd7cdcfb1006109"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "d11321eb2fb39eb542a81d47b67d9860f24f01e631f6565dcb17a37da9eec4b9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "27b9491897f7999c648d8de9e6f640dbfba70882"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "0ee21e9b736276728ab0d2830892fdc3466fd2e554fd6a2655f79ffe6fa487c9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "e24d273463b4a21107932fa34956b6ba61bd792a"
os = "macos"

    [[DAQP.download]]
    sha256 = "2006372cb6afd90b72b6c72f9036267bb6301cc21e93fe6bd336919af6549007"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "c490771866ed24eec391ccae12514cfa0ecddeeb"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "7b07e2a2f1d1b8e8c374acdba7bfe265b04b3c0476dd44ba325b8288e183c7ee"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "47e09ca4134a7fe846ff9496b12bc0adcf4f8556"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "f5989c06922a136aca4d268099520df8833581aaa4ad19dd1cd23e1f0f3ba790"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "705264857a85f615317ffef66e758ec975255439"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "fd85e4b3c78ae33b0673a207f2bfc333cfe770c1d759deb53eab666f7bb2e4bd"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "219399632fd660cb726924d271b5f29e61ac2399"
os = "windows"

    [[DAQP.download]]
    sha256 = "b2d828b5651d85f19de16da786800110acaa11e0747a8583b78c51c2192922db"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.8.4+0/DAQP.v0.8.4.x86_64-w64-mingw32.tar.gz"
