[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b4cb7900b437206978b59551323158e711cd6008"
os = "macos"

    [[DAQP.download]]
    sha256 = "9faf6380a1bd26282709e8d1e963b400e6422bcbc9200c36fc133d6b1165be7a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b7a7a3b48684bd77d2af68e316c88fe7ba67e8c4"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f0d14a88b089b90d20c1b42516c1faffa5abdfe058a733388ab561d4479c67e2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "8675b5500dba1a68821acae4c363d56dd5194627"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "a887b6ce6b86f20d9aa491633c8f1d7074298dc9e594973ea3c29ede2dcdf571"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e5fe239c2e55a392ff7f676194c70b962249d23"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f2e1dcf78188611de9dbce26f48a4be0745eaf8959b2eb1c37ad9902f4f30f4d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3d2392ff484ef9b33b20962004bb020af0bb6f3"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "cd2186e12a766f997c66633ca47e9238cf5dac40f58d381da071897ccdaecf1d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6aa22f0ffd8eb56847bdb8d08ff25ae79e1651fb"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "b3d0f34ddff08fd38b8257a530224af13a8bc1ab4d16f87e2c3c253de8ddeb75"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38db53c45f5a23279a963897a50d460c926087d2"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "c232372cabc1374f0ab03925dfa62d37d9456adb25345655b08f245dea9ede8b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "1951a884e890708d877831d0834f2dc47ed8a5d0"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "2f808d26ed1f1c2e647f5b14e6b5ce888928f4c16d0c819574a0ab7061c54677"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "9379564fbc8409deddefb85164c8f6942d18da68"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "6dbfd03e45e9f639255fa4c90d7cc67cbabdbf039fc2f44b97e1fbc29e9b7332"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "09763e435da381cf7b1d56891d4869cd8b283558"
os = "windows"

    [[DAQP.download]]
    sha256 = "9bd2e0a93b3d3ef69bd8bf588dae193e09f3f097e8376a25f10ee2b16360f391"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "77b0ce14278b6feabb02d21d208e140695aa41e2"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "811e4c2f39d8dd26518f8ce60612f42682b1722980c15c9b1a2d5ec8d4de82cb"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "9cfe14cc1272a6ced7913c6ea35b2986bcd5243c"
os = "macos"

    [[DAQP.download]]
    sha256 = "3271caef797ea9d97de084bf4d618fa1b80e145c7b4d6c8c48af3227014a7423"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "54003d3777974c0d7de57aeaca3078407494094a"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "1d4633d9ef03c7d4b0150fcdcc5915a0102c3aefa919f85c720efb97ced7d009"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "ce626c3d78bbaf8e4e8d541244b1868cd59d96ea"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "6922c19d9efd1f73a157906e70184cfb6b1d5e5b6664109539a1749def049639"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "957f685208da466ca8468dbe4e7f86c1478b3a2f"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "692687ae444e001a371ccbfe33533c2a71e76153a2f1c9b98cb4378068322da2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "e2be9de2f74d46a4989ba5145e76de0b1139c4b8"
os = "windows"

    [[DAQP.download]]
    sha256 = "f2751fe8d5adb67c74645804415250a7a098d656e82fd84533de8637a5c10722"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.0+0/DAQP.v0.3.0.x86_64-w64-mingw32.tar.gz"
