[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "9503742c1a64d4e178f330c41df24a550ab8e679"
os = "macos"

    [[DAQP.download]]
    sha256 = "e0ae4234b3cef379d2de50f76a4148d8222aee0d2ca02d7a04a3e3cf10cb01a2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "666693ffe5cd3337b98d8524d1b990e917cec733"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "c56f51026e605ced168e1802e30bbaa023493fdc6e19f7ec845e4853ba01fcd9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "eaea137c7b89d4452a7a9c7dff0b446ac519fe31"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "228542768ef652ba0b01322b58078d9c4275f5cb176b317681a1a7f3413c70d1"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5120af08fd5d9f76a548d4f8983e0ebe2efd7c79"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "3dbe463ec120f14581f2fd159fb6f2d88e252e2baaa5a9466d1e76731bc7e029"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08053fe363d040480a1779e9f547da2d7a475512"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "d4a29ab63716ac874e69b07a0c890f535448f5d974543200ae8abbfa58b91903"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "110997ef2607acf23f0faa91e1428bb4e935ef55"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "2e46ef33fa615f012be8e5af3cd9d2c900dbe4b73072d5808d33c1e4286c5183"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec53949a2980fce3c4278e0204c2b26733dcc1c9"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "452689c07102d8cf98e6e36e47ff63723d55be0b7c9bcdd825a092b01fafd37f"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "e64a9db1b46b130ce2997bfc4f35627ab23160fb"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "3bf4fbddc2294ae46c9de36365331a1da4c77e635cefa0149d187fb2a8cf287e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "6ba2e3fc8a46e9dc1a99f2322efb557191036f99"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "d662c0a89df968d84ff5312589ee03b4edb33862500108d9a748c6ef5a4a5b3e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "c9aefd315a7b4d9e21a63f49e7726e2c33c8308b"
os = "windows"

    [[DAQP.download]]
    sha256 = "37d2fa37e0452f790eaa98bdd079c4472660bc38803e46d4d3702e8afdf28c89"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "d8babea284f280500660616c05b5d07155d30918"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "b155a4b7f2a45bb62f584be61883ea10f65e6a9af8370a6bf8ad8fa8464d131b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "fc999258cc5bdedbe158181f9b5afbddfc6c9f4e"
os = "macos"

    [[DAQP.download]]
    sha256 = "751ccc8b61b129d6e29323469d8e33437de4c585197412b4e82653574c22dbe6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "835e6be3b344d3e7da1dfa689b9bdaa89d386edc"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f783824b1e5904272b87b2db74251b2ec743d80774b1594604adead9091e657f"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "ff73c017b363c5688fd98bd66994d19d6a5e3927"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "111997132836c1ba1b3a22e8464e3cc0d5162bd5ebacd817680a131f49e66860"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "73915e314a3e66c3f054bfa6d0c01ae406a6610a"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "a71ddbbb3fe1bcd9dbb4e33b3b602aaaabd865a7ad52a0e8a889f65b65ef0b4d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "9df61793fc751bda1c0c32656b8721ca52a936a3"
os = "windows"

    [[DAQP.download]]
    sha256 = "73264d2f830d86a64bc3143fefed3669ce372d38d89688493591a1a9e5e4b845"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.1.0+0/DAQP.v0.1.0.x86_64-w64-mingw32.tar.gz"
