[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b90daa46ed5e32d1eed09aa770d16579a042cd11"
os = "macos"

    [[DAQP.download]]
    sha256 = "8f6fafdd3265fa0d05539dbd7214c5a7b9f381efd50d445717099d73a431a899"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "06a203280bd00c7e04b9502e23c14170fbeff3f3"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "43b285ee36df3804bbfb7439fc3c768fc54715fe3ca1d9d3b043a8aaee92a944"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b270919f1d4b98978e188acf2e76cbbd6bde5a19"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "b8bf5f671895a375dcce54060d6febe31a66f4b53dd1b29cd74f6d53ab4268d2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf6f17ad045cbe2e0e30db7314e4aec36bb3b112"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "1ac71fdfbcf98437a9b9360798025c10678c5978d12b4b9df522c58c728982b2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af8d7e3d4c1ff594b3d37a8b687bc00495567267"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "d40a6e0bf10b4e8358d3b42989987e6ffdefeae087d38248ea31f37815f74377"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0278a45dba7c33ff3088954fe82bc9684f246dd"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "9a9c42e5a060cd1a40393a6a942dbf22306c8833c0bfd8b7ef9cc17a0e083f11"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2d6893266b608ffcf1fc6fdb7dfd5deda474fe6"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "9aecc1b542feea5e8b1a437d9574e144445ae10a1cd7b7f2a5f7d383071e9832"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "b8e3cb3c0fc833ca003c290ebeb1c4d3811061c1"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "70d37aa92273ff1b8dbd00e00625d46bd644884afd7baf3677148dce8802c02a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "34bc9d82a9fc195a8abd64c7c5a3b6ce4817f829"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "2f98df38b0b52806ab0900ad22d39e95263ef7c86f69138220d16d810ac02533"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "a63252d46faa464e8a0380216f0c7019d34b4576"
os = "windows"

    [[DAQP.download]]
    sha256 = "20acad5381f64c40da3ddd7c1dc1895633fd7368f4b8b0edcf8ca12fc45ca8a5"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "de12a129bbe3cc0f25f9bf76d39efc2315468bfb"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "6430d931fc696e16f9139fa5e7498e2c8884b638d5a311392db34413b5e0975f"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "e56f8468611a0d7e38dfa31ea76968b4bdce440d"
os = "macos"

    [[DAQP.download]]
    sha256 = "60c29fe268fdea6834e1410741776fa6fd260852b1c7be88202a6796c2472d62"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "5f8f93e84f94d6ec4af09fd77c63f60fe5b7038f"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "1484c72028d31ebad4bc896e947ebbbdebb7c73d57f1e262030eabaf6a9410bb"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "7828294305345a11dee7280b2adc23ebbda05706"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "9e50796c361e83e55ca079a149a68a97bfee706dd939435c6aa6c9587ad9cf6a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "70e33ba9527232869e75b5b7a00f45ab13b751fb"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "fdfd254b2d2124a6574de9701d26c318b619e64ccec01055b63c5f31b9cf63c1"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "67c6df9cf2740bc9e21e608d79c09255b58bd6c9"
os = "windows"

    [[DAQP.download]]
    sha256 = "bf01825378dad69812cc42a1a3b08bda35ceb5d3cf3ff30c16acb078a7c8c9e4"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.2+0/DAQP.v0.4.2.x86_64-w64-mingw32.tar.gz"
