[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "b68e3fbb44833e773fe06a548e1738162b376d65"
os = "macos"

    [[DAQP.download]]
    sha256 = "b7013d2e675239dfbf206fe75405c4a69f89a4ea34b52128f8e27a85ba3e3c4d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "c0b26b2440dcfe79733c7ef72a41191eb07be9db"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "33d7ccef5c2e0cf7ac654a70d69ad4cb1b2e4fc1957959fba5566b8460e8ec29"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "f89b3069a333fedfbc2cf8412b2738c752042d19"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "ed807d08a4dcb9b119734e2aecb372249568870888f18ea7f49830a31ddcfe09"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "566896d5ab663e31b414e849c85b8505c548f5fe"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "24181850fde69f6d98c29ca02b4c605dbe1d7b2ce9228ab73b2e553786379ce2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3361513e83a843e8ad6cd668a45312e5272cadef"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "26b9119d08d0e5880bd29ba9dbfd7b01ed72c83f3d93ddd3b0ea6ab12ba6f60e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "268177a596f5ed20f0d0e4ce8b40a2f9c00aebaa"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "30b7fee21c477fc51db2fdc13b07ce4469adc66006447dccf9f507df28618026"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8920351f5268c7c4c8f06fab697844af39a375ed"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "096e35ad60187ba0d21ff1dd3619653362c4dc5438e119e1e558c9e9012e9a37"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "32c5a0d968a1d185b176ec4a3ebe8731b4df1c9d"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "4d037967e9f465a8df69c4833ea9f364ceb9683bba27c60ad49c614c9004a548"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "d412948bc25a562fd6eeab9f766c097ef9799831"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "7856b9a0870988f0ce4dd20188192cc7126c42d160868c6b518eaeb340019844"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "d38af04d381460a2193c1fc6c6b957cd921e6571"
os = "windows"

    [[DAQP.download]]
    sha256 = "46014394b241b76ab14314c348ab341876c6c4f22c6fea778524822640ec4633"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "0abfd950b4b0ce42ecf02e03a69dbc4a7ba4eba1"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "153baa6cd087b99d4e88127fe3283a8f9b131909a5f15ccf8d6cdc478a7bd9ac"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "c184194e389fe9c3b5219cc07614605acaa4e8a5"
os = "macos"

    [[DAQP.download]]
    sha256 = "62a67d8445e7dfd36e4d746721aa88fc4a0abe31f05f5cc36f4a939aaacccaed"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "2e2b9083bf96c231e1b7e956d4da0cbb26baa31f"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "e7118112637b5901d0f47066fcf012049cbf2e1b21a0b128d10278b9076a2adb"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "43867c7462252f8a82a69eaf3c9811c6e8157039"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "4b4c9a0d305bf98c4a2924244e952650ee7828e49859423651b6a17115e83bcb"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "e1773b2a1cbd7e43011ed9501ba7443c60e432d5"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "b2e7c4c865addcc075d9e249aeee423c38974eb979a630c98a3b0831d056c328"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "f6ff6add8cbe2fb8ebea3f6ca7764e1cbe91da8b"
os = "windows"

    [[DAQP.download]]
    sha256 = "94e92d133db0730debc8811f0c6f384a8ebe77f6b433249b05f134530e2268e1"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.4.0+0/DAQP.v0.4.0.x86_64-w64-mingw32.tar.gz"
