[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "90888d542e7f439aa29b95d647a6875785506322"
os = "macos"

    [[DAQP.download]]
    sha256 = "a64957cc43db8662dc1d28d64e82195ed430f4aca58f77964a59297d26ec9f11"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "3316eafce02beb0fdd49dbf10fc8f1461e30d4ea"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "61ebe71fe0b07d730fcadd1d036e47a166e9cf30ad9945cad6c735a9241ff2c7"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "5bb4f8e0e6eeac3e5154e0a8e0164cbc761d8197"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "20d1c38ea297d99281d1ddc1fd41230229b47f55e57f2055d27a9ab45f8c9bf5"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c51279eaebcea3303969f165041dc49d8a3c9f7b"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f3e283fc3ece2bc56b4a8def9950f7b05cc6e842980668861a985efb3b302186"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6958b67825b753b8b8a9e8bea2307e68c8a056c"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "3509673e303b03c06dd8d615722408c1c8b69fb6d2d535b701dea1cfcdb2a881"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43c18263f5f97735439ea29baa0320ecc9e0197e"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "35a0fddee29c99348d00c72a75312247d1e653b1c3a40b9dedd9c9708ccdaee5"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cefd7a431c90beb413c019875d54c0a50f89c26c"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "d987105ced68b010bbdaffa450588053e798a8441e4d4c72bf7d27f3e1243309"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "4c0e7c6e80a70e98f2c0a155811ea480ac613f9d"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "02c7836107691bb819082c10f159506234ebeed62042f8de83bf7e2615316089"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "208760f5e063a86365dfe163654e55040233854a"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "a3b377ffe35b4d57b685bb98e73d0b314a947236126394e5afcb80a37b66fd99"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "e27e3038d3c53da813203b46b9a3191839be9900"
os = "windows"

    [[DAQP.download]]
    sha256 = "5cab87b20356281d22c4399ed0cb8c2fff47aed9ff67b3a24810d8088cd5fdd5"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "ab994339a0b8c5972736c7ca10e4f8d1c1ec526c"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "6dae49cb7cf7611b75144561337a54de921817f599e4b89ffae0b4b17ab1783e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "b7b7bcd600788477af875927a67fd3908a3f7cc6"
os = "macos"

    [[DAQP.download]]
    sha256 = "e0b8264a7fb87607dc5ac85d608f22f00a5fc67984bb480982419644f9862f7b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "647674b66a409e589af7c5a92f61b7a51cc39c33"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f3ea662ba703096247d1365816858e8b4f1c22bbb660c74250cec4c3fa775a91"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "158c65ac8cd3b65076d9a0e6b7389c832912621a"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "9e501c431efa0749f5ee0a21c1b955509e88f269bc284607c8dce67edb2cabd7"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "23798c28f835e6f78f33e5740b7d39b447cee1cc"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "cc68493c58f2b8ca64020887c67d168f3fe49cab753248b1598d036ca9ddbe18"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "baba18b47b18031e082622eb12c52393684575f7"
os = "windows"

    [[DAQP.download]]
    sha256 = "c0e2d78f0fbdb954ff5719a8e3cab1a0e23be11128a2329c65fd49524dcdfefa"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.3.1+0/DAQP.v0.3.1.x86_64-w64-mingw32.tar.gz"
