[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "95f991604de9092a9a832923919ca30f94c7be34"
os = "macos"

    [[DAQP.download]]
    sha256 = "fdf4da3149eef19ffa46e2609a7b6c3c2b8c42450fc8c30a19cf6675c3229737"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "8e338fb6c905a2dfce2b867e1e7cad22a4cf7e92"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "da9ee565b76eb2bb0d802079be727f263dc01a3c0266de20d18ca562c6a8f8d6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "e5d7bdd3ceabf9913fb028223f600c45adc5d652"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "27316a67c74a69b2fa32baf9da51756ff8524fb4d09c417fed2ac9d072f66b9b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f1f44ad98ea597919fb906045d71497e5938cc9c"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "bcc1bc3ff8dfdb657fa2111287cb6990693268ceef8dc109437683cbd06885df"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67ceab6c9725cc5c0e03a7f6dd0d04a84254ad40"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "50624ef7c9bbc4c747b30a35813801b35499cbe2a27f2ffccf99d1c091f75439"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "84daf8f006e84751e0bf85b95fca6e0e4ef74a70"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "aa04224cd0792c79ba777ed08255bd9130afca46f4ffb5f0e4a31805941c2fc9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b4e719520514ccd4b73090014107058bc212dfe"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "c249591bef77d68d0a2583d478899e93c90f75da116f747e2beead5f6cdf660c"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "8af771e9512862085aa02cf287395e44ada6309e"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "2895aca22fcda5ab36240e879698523390f04096479d52fe01c8855ae84692e2"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "d5be9bd635ad49178d51f5115fd16d84c62e9a45"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "eb80efcf24ef36b19056da6fcff55b6ce6a92029440b04e8a33c2c914873fd71"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "349dc61b134a84a849397affd166f0d2266b12b2"
os = "windows"

    [[DAQP.download]]
    sha256 = "d3c36197f4ab5f7eba72519978fc514a79c139689a3b596ce9c05c9d37c6a3fb"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "932945dc3c2e0a5af87d3c2bb756cadf7b834a31"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "41f6cff647e54bcb89b5519861846e3b24cebcced321ba6ab71b45e3d0468df4"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "7f0995d98b30fa6fcf684ab79c8bd09d9735179e"
os = "macos"

    [[DAQP.download]]
    sha256 = "f0498e88305b7806b7788633bd3695c1ea4a17d7af0eec6b7df6cd2884474237"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "ab9e5f693e33d5d04fa90e7324f966a361b81bcd"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "26df3fdde584be22701a213835e0a6834d662f1fb238266054dbbd1590b7a301"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "fe828bbfb3795d001ccb6b23832607057f42f255"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "1434dd7b9c6eb94b1d9388edf88f0bae867d6535b23ed27109748ea6d7e3631e"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "3bdc59bb296f5c56e34c4237c273a12aff49807f"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "a5739f9c9b3fb940352e0358dbe88887d4f23ebdb209cb5627fee18ebe7efc3c"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "8bdecc3fc16e1f09de7708518301f185a3e8c78c"
os = "windows"

    [[DAQP.download]]
    sha256 = "4872f5899bc3e43bf57d7da9e10c3887200996df0fd5bc6259874d76e24aaf0b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.5.0+0/DAQP.v0.5.0.x86_64-w64-mingw32.tar.gz"
