[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "dca874d0f8e76f6d5531208b20f1d565e46d1b4a"
os = "macos"

    [[DAQP.download]]
    sha256 = "8451ca528fa3f91afdba02a1c612207aeb01471b1b7d840e2860d20307a89380"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "bb127575a291bb46aa75f2b2f6fbe1b924cfbfd7"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "3a05699e713f7fbcc62fa74ec6b3ff966ed15c29aff4bb27ed3dbdfe36c39281"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "9609942cb927088f7061fde9f11b3c80784cff76"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "a69be8f601a0318b570fee31f85f9ceaed27fa1bdb6a3b0bed961cd4498c891b"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "540d04903eb7865efbb3f6d51a0710f1972270c2"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "9fd032de15983384add00edea4d8db35306ecbb9a60077dffd8c0e3649384e25"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21418e6806b2e2b03c46efd2b36c8f5331dcb307"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "0526bb4df828b7d93f37e029966755f6cd3fd15eeb9e564b866cfe8a468921d1"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2236ddb226c915a6afd4d14ad0fe7f67e6de1af"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "30687c54ac04b9cf3ba4a278869ca802881908e433a88253fa54b05720ff30b9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9038666692d75f01d6be0df67183f08a8315f16e"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "910e730a2a75fb2609c55ea15f71e3cd837bbd25a735710fdf0a0cd32232b913"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38eecdee0c888e03b7104c1a03c976650dab7a40"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "c573ac5129b18598b834870196fbad8ab9a2a067868cda498cfbf9cb97b22fb9"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "aaf8ffdb5153dd7881f39aec00ee76c4f7da9c21"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "3d3d070cd286466e0b5c9148f2f05404d668d8e989cbc758ab8e590d843b0765"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "8510a7fa212993435dd1c9cb6bd95e183df3459e"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "2feeb6abb3a7d6332d6dc052a41eabc93f8d71132ce1252b3efcde2ea3c56cb3"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "c3e3430904c3d145da9acd7fffe07bb50d851960"
os = "windows"

    [[DAQP.download]]
    sha256 = "a7d680325f0898be4f24c71c140c49ac287c94855fd1263cbe6b7650f963ce6a"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "870a6efedee8cbcf3e22094e203b1ce82f343f5e"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "15a69b2f606f300f87be3c9cfc66b6cc92dd7fbf73c22747825ef8177de92903"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "2aad0239433724c2d8ddb0df2800010876794648"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "b758722eebc49474050b4e4c494afabac086dc19daab57adcfad582fec013313"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "e8c2bfa6e8c1c2893e3b0e27b4c5a6cd87c24663"
os = "macos"

    [[DAQP.download]]
    sha256 = "57b03c3ea80d3b277a74dab79583d6b0e087af1d158b1a6a3d1f1aef836496bc"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "28b80d151fa9f4e653065bce3908629d8a9e9136"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "1737b976b1579006b7f00da46414c18e49ea397571656550afcc36f0a317fab6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "435aa6d467783b0e757e4db5c645b1f76e861d1d"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "a09fc94fcf353289269d4d1962414b594190b814b28c3d6ebcab87b114f44068"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "b4914a65dbf4544d7cfb354b6870d9d724e176fe"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "25feee9afaac80ed776388f0de9a9af8e8395b2b397a6a2b1db714260e4ec10d"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "321d1bb1251ba5d602d564900befbbf9ce015773"
os = "windows"

    [[DAQP.download]]
    sha256 = "5e5e43251144c77e16893ab741007917c6f28b9ee06192d4a03c74e0fea126d6"
    url = "https://github.com/JuliaBinaryWrappers/DAQP_jll.jl/releases/download/DAQP-v0.7.1+0/DAQP.v0.7.1.x86_64-w64-mingw32.tar.gz"
